export interface ClientSite {
  id: string
  name: string
  comaxId: string
  district: string
  address: string
  city: string
  lat: number
  lng: number
  status: "standard" | "problematic"
  contactName: string
  contactPhone: string
  craneBarcode: string
  flatbedBarcode: string
  craneUnloadMinutes: number
  flatbedUnloadMinutes: number
  distanceKm: number
  paymentTerms: string
  surchargePercent: number
  basePriceNis: number
  observations: string
  riskDetails?: string
  preferredDeliveryHours: string
  hasExactGps?: boolean
  gpsCoordinates?: string
  gpsSource?: "sheet_col_p"
  ituranCraneAvgMinutes?: number
  ituranFlatbedAvgMinutes?: number
  verificationStamp?: string
  crossValidationNote?: string
}

export const RAW_HISTORICAL_63_CLIENTS: ClientSite[] = [
  // --- 1 to 15: השרון (הוד השרון, רעננה, כפר סבא, הרצליה, רמת השרון) ---
  {
    id: "saban-1",
    name: "אחמד אבו חדר",
    comaxId: "10452",
    district: "השרון",
    address: "שחף 9",
    city: "הוד השרון",
    lat: 32.1465,
    lng: 34.8912,
    status: "standard",
    contactName: "אחמד אבו חדר",
    contactPhone: "052-4418902",
    craneBarcode: "18101",
    flatbedBarcode: "818101",
    craneUnloadMinutes: 15,
    flatbedUnloadMinutes: 12,
    distanceKm: 2.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "גישה חופשית ונוחה מהרחוב הראשי, שער חניה פתוח לקבלת משטחים ישירות למגרש.",
    preferredDeliveryHours: "בוקר מוקדם (07:00-10:00)",
  },
  {
    id: "saban-2",
    name: "ד.ניב / חינוך מיוחד",
    comaxId: "10834",
    district: "השרון",
    address: "הבנות 16",
    city: "הוד השרון",
    lat: 32.1521,
    lng: 34.8945,
    status: "standard",
    contactName: "דני ניב",
    contactPhone: "054-7892110",
    craneBarcode: "18102",
    flatbedBarcode: "818102",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 1.9,
    paymentTerms: "שוטף + 60",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "מול בית הספר, פריקה מוסדרת במפרץ פריקה. מומלץ לתאם הגעה לא בזמן פיזור תלמידים.",
    preferredDeliveryHours: "לא בין 07:45-08:30 ו-13:30-14:30",
  },
  {
    id: "saban-3",
    name: "לירן / מוצקין",
    comaxId: "20419",
    district: "השרון",
    address: "מוצקין 22",
    city: "רעננה",
    lat: 32.1852,
    lng: 34.8711,
    status: "standard",
    contactName: "לירן מזרחי",
    contactPhone: "050-6543219",
    craneBarcode: "18103",
    flatbedBarcode: "818103",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 15,
    distanceKm: 6.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "חצר אחורית פתוחה, מנוף נפתח בקלות מעל הגדר הנמוכה. גישה טובה למשאית 12 טון.",
    preferredDeliveryHours: "גמיש לאורך כל היום",
  },
  {
    id: "saban-4",
    name: "לירן / ביל\"ו",
    comaxId: "20420",
    district: "השרון",
    address: "ביל\"ו 53",
    city: "רעננה",
    lat: 32.1812,
    lng: 34.869,
    status: "standard",
    contactName: "לירן מזרחי",
    contactPhone: "050-6543219",
    craneBarcode: "18104",
    flatbedBarcode: "818104",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 5.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "אתר שיפוץ פעיל, פריקה ישירה לתוך שטח המגרש. שטח מאוזן לרגלי מנוף.",
    preferredDeliveryHours: "בוקר עד 12:00",
  },
  {
    id: "saban-5",
    name: "אורניל / אבי לוי גור",
    comaxId: "30112",
    district: "השרון",
    address: "לוי אשכול 14",
    city: "רעננה",
    lat: 32.179,
    lng: 34.861,
    status: "problematic",
    contactName: "אבי לוי",
    contactPhone: "052-8883210",
    craneBarcode: "18105",
    flatbedBarcode: "818105",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 30,
    distanceKm: 6.8,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 480,
    observations: "רחוב צר, רכבים חונים משני הצדדים. נדרשת זהירות יתרה בעת ייצוב רגלי המנוף על מדרכה.",
    riskDetails: "רוחב מעבר 3.1 מטר, כבלי חשמל עיליים במרחק 4 מטר מהגג.",
    preferredDeliveryHours: "10:00 - 13:00 בלבד (לאחר שחרור חניות)",
  },
  {
    id: "saban-6",
    name: "עומר השרון / קפלנסקי",
    comaxId: "10992",
    district: "השרון",
    address: "קפלנסקי 8",
    city: "כפר סבא",
    lat: 32.174,
    lng: 34.908,
    status: "standard",
    contactName: "עומר שפירא",
    contactPhone: "054-2211993",
    craneBarcode: "18106",
    flatbedBarcode: "818106",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 4.1,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "בניין בבנייה, משטח פריקה יצוק מבטון. מנהל עבודה במקום עם עגלות משטחים.",
    preferredDeliveryHours: "07:00 - 16:00",
  },
  {
    id: "saban-7",
    name: "סער הנדסה / כנפי נשרים",
    comaxId: "10744",
    district: "השרון",
    address: "כנפי נשרים 31",
    city: "כפר סבא",
    lat: 32.1695,
    lng: 34.921,
    status: "standard",
    contactName: "סער כהן",
    contactPhone: "050-7766551",
    craneBarcode: "18107",
    flatbedBarcode: "818107",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 4.9,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "הפריקה ישירות למרפסת קומה 2. זרוע מנוף נדרשת לטווח של 16 מטר לפחות.",
    preferredDeliveryHours: "08:00 - 14:00",
  },
  {
    id: "saban-8",
    name: "גילת שיפוצים / גולומב",
    comaxId: "20815",
    district: "השרון",
    address: "גולומב 19",
    city: "רמת השרון",
    lat: 32.1432,
    lng: 34.8385,
    status: "problematic",
    contactName: "אלירן גילת",
    contactPhone: "053-4455667",
    craneBarcode: "18108",
    flatbedBarcode: "818108",
    craneUnloadMinutes: 40,
    flatbedUnloadMinutes: 25,
    distanceKm: 7.5,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 480,
    observations: "רחוב צר חד-סטרי. פיקוח עירוני קפדני מאוד. יש לפרוק במהירות ולסגור מנוף מיד.",
    riskDetails: "חסימת נתיב מחייבת מלווה עם אפוד ומשולש אזהרה, סכנת קנס עירוני.",
    preferredDeliveryHours: "11:00 - 13:00 בלבד",
  },
  {
    id: "saban-9",
    name: "אביב צמרות / סוקולוב",
    comaxId: "20930",
    district: "השרון",
    address: "סוקולוב 88",
    city: "רמת השרון",
    lat: 32.148,
    lng: 34.841,
    status: "standard",
    contactName: "יוסי אביב",
    contactPhone: "052-3344556",
    craneBarcode: "18109",
    flatbedBarcode: "818109",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 6.9,
    paymentTerms: "שוטף + 45",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "רחוב ראשי, מפרץ עצירה ייעודי לחומרי בניין מאושר עד 30 דקות.",
    preferredDeliveryHours: "09:00 - 15:00",
  },
  {
    id: "saban-10",
    name: "הדר וילות / הנשיא",
    comaxId: "30240",
    district: "השרון",
    address: "הנשיא 42",
    city: "הרצליה פיתוח",
    lat: 32.181,
    lng: 34.808,
    status: "standard",
    contactName: "רונן הדר",
    contactPhone: "054-9988771",
    craneBarcode: "18110",
    flatbedBarcode: "818110",
    craneUnloadMinutes: 35,
    flatbedUnloadMinutes: 20,
    distanceKm: 11.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "וילה יוקרתית, פריקה מעל חומת אבן לחצר בריכה. נדרש ריפוד גומי לרגלי המנוף למניעת שבירת אבנים משתלבות.",
    preferredDeliveryHours: "08:30 - 16:00",
  },
  {
    id: "saban-11",
    name: "אלון גבס / בן גוריון",
    comaxId: "30315",
    district: "השרון",
    address: "בן גוריון 33",
    city: "הרצליה",
    lat: 32.164,
    lng: 34.842,
    status: "standard",
    contactName: "אלון שרעבי",
    contactPhone: "050-1234567",
    craneBarcode: "18111",
    flatbedBarcode: "818111",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 15,
    distanceKm: 7.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "משטחי בלוקים וטיח, פריקה על המדרכה בתיאום מראש. עגלת שטח במקום.",
    preferredDeliveryHours: "בוקר מוקדם (07:00-09:00)",
  },
  {
    id: "saban-12",
    name: "ברק שלד / דרך רמתיים",
    comaxId: "10101",
    district: "השרון",
    address: "דרך רמתיים 102",
    city: "הוד השרון",
    lat: 32.1585,
    lng: 34.8895,
    status: "standard",
    contactName: "ברק יצחקי",
    contactPhone: "052-1122334",
    craneBarcode: "18112",
    flatbedBarcode: "818112",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 1.4,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "מול קניון מרגלית, כניסה מאחור מרחוב הדקל. פריקה קלה מאוד ומהירה.",
    preferredDeliveryHours: "כל שעות הפעילות",
  },
  {
    id: "saban-13",
    name: "תל מונד ירוקה / הדקלים",
    comaxId: "10555",
    district: "השרון",
    address: "הדקלים 40",
    city: "תל מונד",
    lat: 32.257,
    lng: 34.921,
    status: "standard",
    contactName: "יפתח רווה",
    contactPhone: "054-5544332",
    craneBarcode: "18113",
    flatbedBarcode: "818113",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 20,
    distanceKm: 15.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "שכונת הרחבה חדשה, דרך עפר כבושה, אין בעיית מקום או גובה.",
    preferredDeliveryHours: "07:00 - 15:00",
  },
  {
    id: "saban-14",
    name: "קדימה וילות / האתרוג",
    comaxId: "10612",
    district: "השרון",
    address: "האתרוג 12",
    city: "קדימה-צורן",
    lat: 32.274,
    lng: 34.912,
    status: "standard",
    contactName: "אילן מרום",
    contactPhone: "050-9876543",
    craneBarcode: "18114",
    flatbedBarcode: "818114",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 16.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "כביש רחב, פריקה מעל חומת בלוקים לחצר פנימית.",
    preferredDeliveryHours: "08:00 - 16:00",
  },
  {
    id: "saban-15",
    name: "אבן יהודה בונה / העצמאות",
    comaxId: "10780",
    district: "השרון",
    address: "העצמאות 55",
    city: "אבן יהודה",
    lat: 32.271,
    lng: 34.887,
    status: "standard",
    contactName: "עמית בן צור",
    contactPhone: "052-6677889",
    craneBarcode: "18115",
    flatbedBarcode: "818115",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 17.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 480,
    observations: "בנייה כפרית, גישה נוחה למשאית כבדה, שטח מישורי.",
    preferredDeliveryHours: "08:00 - 15:00",
  },

  // --- 16 to 30: תל אביב (מרכז, צפון, דרום, יפו, רמת אביב) ---
  {
    id: "saban-16",
    name: "רוני שיפוצים / פלורנטין",
    comaxId: "40102",
    district: "תל אביב",
    address: "הרצל 78",
    city: "תל אביב - יפו",
    lat: 32.058,
    lng: 34.771,
    status: "problematic",
    contactName: "רוני אברהם",
    contactPhone: "050-4443322",
    craneBarcode: "18201",
    flatbedBarcode: "818201",
    craneUnloadMinutes: 50,
    flatbedUnloadMinutes: 35,
    distanceKm: 19.5,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "סמטה צרה מאוד, חוטי חשמל עיליים צפופים. עמוסי פריקה וחניה כפולה של מסחריות.",
    riskDetails: "פתיחת רגלי מנוף מחייבת תיאום עם משטרת התנועה או פריקה ב-06:00 בבוקר בלבד.",
    preferredDeliveryHours: "06:00 - 07:00 בבוקר בלבד",
  },
  {
    id: "saban-17",
    name: "תל אביב בינוי / דיזנגוף",
    comaxId: "40210",
    district: "תל אביב",
    address: "דיזנגוף 182",
    city: "תל אביב",
    lat: 32.086,
    lng: 34.774,
    status: "problematic",
    contactName: "יואב גרשון",
    contactPhone: "054-6655443",
    craneBarcode: "18202",
    flatbedBarcode: "818202",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 30,
    distanceKm: 18.2,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "רחוב עמוס, נתיב תחבורה ציבורית (נת\"צ). פיקוח תל-אביבי אגרסיבי במיוחד.",
    riskDetails: "קנס אוטומטי במצלמות עירייה על עצירה בנת\"צ ללא היתר פריקה מראש.",
    preferredDeliveryHours: "09:30 - 11:30 בלבד",
  },
  {
    id: "saban-18",
    name: "אורבניקה / בוגרשוב",
    comaxId: "40315",
    district: "תל אביב",
    address: "בוגרשוב 45",
    city: "תל אביב",
    lat: 32.077,
    lng: 34.77,
    status: "problematic",
    contactName: "איתן בר-לב",
    contactPhone: "052-7788990",
    craneBarcode: "18203",
    flatbedBarcode: "818203",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 30,
    distanceKm: 18.8,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "פרויקט שימור מבנים, מעבר חד-סטרי צר, תנועת אופניים וקורקינטים בלתי פוסקת.",
    riskDetails: "חובת עובד אבטחה בשטח להכוונת הולכי רגל בזמן הנפת מנוף.",
    preferredDeliveryHours: "06:30 - 08:00 בבוקר",
  },
  {
    id: "saban-19",
    name: "מגדלי צמרת / נסים אלוני",
    comaxId: "40420",
    district: "תל אביב",
    address: "נסים אלוני 10",
    city: "תל אביב",
    lat: 32.091,
    lng: 34.793,
    status: "standard",
    contactName: "אלי גבע",
    contactPhone: "050-3322114",
    craneBarcode: "18204",
    flatbedBarcode: "818204",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 15.6,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "כניסה למתחם מגדלים, מפרץ פריקה ייעודי עם מחסום חשמלי. שומר בכניסה.",
    preferredDeliveryHours: "08:00 - 15:00",
  },
  {
    id: "saban-20",
    name: "שיכון דן / משמר הירדן",
    comaxId: "40511",
    district: "תל אביב",
    address: "משמר הירדן 54",
    city: "תל אביב",
    lat: 32.112,
    lng: 34.829,
    status: "standard",
    contactName: "דן אלקבץ",
    contactPhone: "054-2233445",
    craneBarcode: "18205",
    flatbedBarcode: "818205",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 10.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "שכונה צפון מזרחית שקטה, רחוב רחב ונוח לפריקה ללא הפרעה לתנועה.",
    preferredDeliveryHours: "08:00 - 14:00",
  },
  {
    id: "saban-21",
    name: "רמת אביב ג׳ / רקנאטי",
    comaxId: "40608",
    district: "תל אביב",
    address: "רקנאטי 12",
    city: "תל אביב",
    lat: 32.128,
    lng: 34.799,
    status: "standard",
    contactName: "מיכאל ויסמן",
    contactPhone: "052-9988112",
    craneBarcode: "18206",
    flatbedBarcode: "818206",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 12.4,
    paymentTerms: "שוטף + 45",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "בניין מגורים יוקרתי, פריקה ברחבת חניה תחתונה. גישה נוחה למנוף.",
    preferredDeliveryHours: "09:00 - 14:00",
  },
  {
    id: "saban-22",
    name: "יפו העתיקה / יפת",
    comaxId: "40715",
    district: "תל אביב",
    address: "יפת 92",
    city: "תל אביב - יפו",
    lat: 32.046,
    lng: 34.752,
    status: "problematic",
    contactName: "מוחמד קאסם",
    contactPhone: "054-4433221",
    craneBarcode: "18207",
    flatbedBarcode: "818207",
    craneUnloadMinutes: 50,
    flatbedUnloadMinutes: 35,
    distanceKm: 21.8,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "צפיפות קיצונית, בנייה ערבית היסטורית, סמטאות ללא מוצא למשאית גדולה.",
    riskDetails: "איסור כניסה למשאית 12 טון בסמטאות פנימיות! יש להשתמש באיסוזו פלטה 5.5T בלבד.",
    preferredDeliveryHours: "06:00 - 08:00 בלבד",
  },
  {
    id: "saban-23",
    name: "מונטיפיורי / בית אלפא",
    comaxId: "40820",
    district: "תל אביב",
    address: "בית אלפא 7",
    city: "תל אביב",
    lat: 32.067,
    lng: 34.789,
    status: "standard",
    contactName: "אלכס פרידמן",
    contactPhone: "050-5566778",
    craneBarcode: "18208",
    flatbedBarcode: "818208",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 16.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "אזור מוסכים ונגריות, משאיות חולפות בקביעות. פריקה עם מנוף בפתח החצר.",
    preferredDeliveryHours: "07:00 - 15:00",
  },
  {
    id: "saban-24",
    name: "הדר יוסף / שלונסקי",
    comaxId: "40910",
    district: "תל אביב",
    address: "שלונסקי 28",
    city: "תל אביב",
    lat: 32.115,
    lng: 34.818,
    status: "standard",
    contactName: "גיא אורן",
    contactPhone: "052-1133557",
    craneBarcode: "18209",
    flatbedBarcode: "818209",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 11.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "פרויקט תמ\"א 38, משטח פיגומים בחזית הבניין. פריקה ישירה למשטח היעודי.",
    preferredDeliveryHours: "08:30 - 15:00",
  },
  {
    id: "saban-25",
    name: "נווה צדק / שבזי",
    comaxId: "41005",
    district: "תל אביב",
    address: "שבזי 36",
    city: "תל אביב",
    lat: 32.061,
    lng: 34.766,
    status: "problematic",
    contactName: "יונתן ברק",
    contactPhone: "054-7788991",
    craneBarcode: "18210",
    flatbedBarcode: "818210",
    craneUnloadMinutes: 55,
    flatbedUnloadMinutes: 35,
    distanceKm: 19.8,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "סמטאות צרות, ריצוף אבן עתיק, בלתי אפשרי לפתוח מנוף ללא פגיעה במרפסות היסטוריות.",
    riskDetails: "משאית 12 טון לא יכולה לעבור בפינות הרחוב. פריקה ידנית או עגלת הידראולית מפלטה קטנה.",
    preferredDeliveryHours: "06:30 - 08:00 בלבד",
  },
  {
    id: "saban-26",
    name: "נחלת יצחק / יגאל אלון",
    comaxId: "41120",
    district: "תל אביב",
    address: "יגאל אלון 120",
    city: "תל אביב",
    lat: 32.074,
    lng: 34.795,
    status: "standard",
    contactName: "עופר שחם",
    contactPhone: "050-8899001",
    craneBarcode: "18211",
    flatbedBarcode: "818211",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 16.0,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "ציר תנועה ראשי, כניסה ייעודית למתחם עבודה דרך מחסום פריקה אחורי.",
    preferredDeliveryHours: "09:00 - 15:30",
  },
  {
    id: "saban-27",
    name: "בבלי / טולדנו",
    comaxId: "41233",
    district: "תל אביב",
    address: "טולדנו 15",
    city: "תל אביב",
    lat: 32.096,
    lng: 34.797,
    status: "standard",
    contactName: "אורי פלג",
    contactPhone: "052-4455661",
    craneBarcode: "18212",
    flatbedBarcode: "818212",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 14.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "שכונה שקטה, רכבים חונים ברחוב, נדרש שטח פתיחת רגלי מנוף מול הכניסה הראשית.",
    preferredDeliveryHours: "09:30 - 14:30",
  },
  {
    id: "saban-28",
    name: "שרונה / קפלן",
    comaxId: "41344",
    district: "תל אביב",
    address: "קפלן 24",
    city: "תל אביב",
    lat: 32.072,
    lng: 34.786,
    status: "problematic",
    contactName: "תומר ברקוביץ",
    contactPhone: "054-1122339",
    craneBarcode: "18213",
    flatbedBarcode: "818213",
    craneUnloadMinutes: 40,
    flatbedUnloadMinutes: 25,
    distanceKm: 17.2,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "אזור עמוס הפגנות ותנועה ציבורית. עבודה רק בתיאום מדויק עם קב\"ט המתחם.",
    riskDetails: "חסימת נתיב גוררת פינוי משטרתי מידי. דרושה פריקה מהירה ביותר.",
    preferredDeliveryHours: "06:00 - 07:30 בבוקר",
  },
  {
    id: "saban-29",
    name: "אפקה / קק\"ל",
    comaxId: "41455",
    district: "תל אביב",
    address: "שדרות קק\"ל 88",
    city: "תל אביב",
    lat: 32.122,
    lng: 34.809,
    status: "standard",
    contactName: "גילי רז",
    contactPhone: "050-6677881",
    craneBarcode: "18214",
    flatbedBarcode: "818214",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 12.0,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "רחוב רחב עם שדרת עצים, מיקום מוגדר לפריקה בחניה הפרטית של הווילה.",
    preferredDeliveryHours: "08:00 - 15:00",
  },
  {
    id: "saban-30",
    name: "התקווה / אצ\"ל",
    comaxId: "41566",
    district: "תל אביב",
    address: "אצ\"ל 62",
    city: "תל אביב",
    lat: 32.052,
    lng: 34.788,
    status: "problematic",
    contactName: "ציון כהן",
    contactPhone: "052-8877665",
    craneBarcode: "18215",
    flatbedBarcode: "818215",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 30,
    distanceKm: 18.5,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "צפיפות גבוהה, שוק פעיל בקרבת מקום, סוחרים חונים ברחוב ללא סדר.",
    riskDetails: "הגבלת גובה עקב כבלי תקשורת פיראטיים בין גגות.",
    preferredDeliveryHours: "06:30 - 08:00 בבוקר",
  },

  // --- 31 to 45: גוש דן והמרכז (פתח תקווה, בני ברק, רמת גן, גבעתיים, חולון, ראשון לציון, ראש העין, יהוד) ---
  {
    id: "saban-31",
    name: "יובלים ביצוע / הירקון",
    comaxId: "50101",
    district: "מרכז",
    address: "הירקון 14",
    city: "בני ברק",
    lat: 32.098,
    lng: 34.825,
    status: "standard",
    contactName: "יהודה יובלים",
    contactPhone: "050-9911882",
    craneBarcode: "18301",
    flatbedBarcode: "818301",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 20,
    distanceKm: 11.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "אזור תעשייה ב.ס.ר / מבצע קדש, כביש רחב עם יכולת פריקה נוחה ללא חסימה.",
    preferredDeliveryHours: "07:00 - 17:00",
  },
  {
    id: "saban-32",
    name: "בני ברק קהילתית / רבי עקיבא",
    comaxId: "50212",
    district: "מרכז",
    address: "רבי עקיבא 95",
    city: "בני ברק",
    lat: 32.084,
    lng: 34.832,
    status: "problematic",
    contactName: "שמואל קליין",
    contactPhone: "052-7711223",
    craneBarcode: "18302",
    flatbedBarcode: "818302",
    craneUnloadMinutes: 55,
    flatbedUnloadMinutes: 35,
    distanceKm: 13.2,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "עומס הולכי רגל, עגלות ילדים ואוטובוסים בלתי פוסקים. אין לעמוד על הכביש.",
    riskDetails: "סכנת פגיעה בהולכי רגל בעת הנפת מנוף. דרושים 2 מכווינים עם סרטי סימון.",
    preferredDeliveryHours: "לילה (22:00-05:00) או 06:00 בבוקר בדיוק",
  },
  {
    id: "saban-33",
    name: "פתח תקווה מרכז / רוטשילד",
    comaxId: "50325",
    district: "מרכז",
    address: "רוטשילד 42",
    city: "פתח תקווה",
    lat: 32.088,
    lng: 34.887,
    status: "standard",
    contactName: "ניסים לוי",
    contactPhone: "054-3344558",
    craneBarcode: "18303",
    flatbedBarcode: "818303",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 8.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "בניין מגורים בשדרוג, חניה פנימית מתאימה לפריקת מנוף ישירה.",
    preferredDeliveryHours: "08:00 - 15:00",
  },
  {
    id: "saban-34",
    name: "אם המושבות / ראשון לציון",
    comaxId: "50436",
    district: "מרכז",
    address: "ראשון לציון 18",
    city: "פתח תקווה",
    lat: 32.102,
    lng: 34.872,
    status: "standard",
    contactName: "רונן צור",
    contactPhone: "050-2233441",
    craneBarcode: "18304",
    flatbedBarcode: "818304",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 7.1,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "שכונה מודרנית עם מפרצי פריקה רחבים. כניסה מהירה מכביש 4/5.",
    preferredDeliveryHours: "07:30 - 16:00",
  },
  {
    id: "saban-35",
    name: "סגולה תעשייה / הגזם",
    comaxId: "50547",
    district: "מרכז",
    address: "הגזם 9",
    city: "פתח תקווה",
    lat: 32.105,
    lng: 34.902,
    status: "standard",
    contactName: "איציק ברקו",
    contactPhone: "052-5566772",
    craneBarcode: "18305",
    flatbedBarcode: "818305",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 6.0,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "מתחם מסחרי גדול, רמפה לפריקה ישירה מהפלטה עם מלגזה של הלקוח.",
    preferredDeliveryHours: "כל שעות הפעילות",
  },
  {
    id: "saban-36",
    name: "רמת גן בורסה / אבא הלל",
    comaxId: "50658",
    district: "מרכז",
    address: "אבא הלל 14",
    city: "רמת גן",
    lat: 32.083,
    lng: 34.805,
    status: "problematic",
    contactName: "ולדימיר קגן",
    contactPhone: "053-9988776",
    craneBarcode: "18306",
    flatbedBarcode: "818306",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 30,
    distanceKm: 14.5,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "מתחם הבורסה, תנועה כבדה במיוחד בשעות הבוקר. פריקה במפרץ טעינה תת קרקעי מוגבל גובה.",
    riskDetails: "הגבלת גובה 3.80 מטר במפרץ הפריקה! משאית מנוף גבוהה אינה יכולה להיכנס – פלטה בלבד.",
    preferredDeliveryHours: "10:00 - 14:00 בלבד",
  },
  {
    id: "saban-37",
    name: "מרום נווה / תרצה",
    comaxId: "50769",
    district: "מרכז",
    address: "תרצה 19",
    city: "רמת גן",
    lat: 32.073,
    lng: 34.823,
    status: "standard",
    contactName: "ארז כץ",
    contactPhone: "054-8877662",
    craneBarcode: "18307",
    flatbedBarcode: "818307",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 13.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "שכונה שקטה סביב פארק מרום נווה, גישה פתוחה ונוחה לחניה.",
    preferredDeliveryHours: "08:30 - 15:00",
  },
  {
    id: "saban-38",
    name: "גבעתיים סיטי / כצנלסון",
    comaxId: "50870",
    district: "מרכז",
    address: "כצנלסון 110",
    city: "גבעתיים",
    lat: 32.072,
    lng: 34.811,
    status: "problematic",
    contactName: "אילן שוורץ",
    contactPhone: "050-3344552",
    craneBarcode: "18308",
    flatbedBarcode: "818308",
    craneUnloadMinutes: 40,
    flatbedUnloadMinutes: 25,
    distanceKm: 15.2,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "ציר מרכזי וסואן בגבעתיים, שיפוע תלול ברחוב, נדרש דיפון גלגלים בבטיחות.",
    riskDetails: "חובת שימוש בסדי בלימה לגלגלים עקב שיפוע הכביש, סכנת הידרדרות בעת פריקה.",
    preferredDeliveryHours: "09:30 - 12:00 בלבד",
  },
  {
    id: "saban-39",
    name: "חולון ח-300 / אהרונוביץ",
    comaxId: "50981",
    district: "מרכז",
    address: "אהרונוביץ 72",
    city: "חולון",
    lat: 32.016,
    lng: 34.774,
    status: "standard",
    contactName: "גדי מור",
    contactPhone: "052-1144778",
    craneBarcode: "18309",
    flatbedBarcode: "818309",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 23.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "שכונה חדשה ורחבה, אתרי תמ\"א רבים, פריקה מרווחת ברחבה קדמית.",
    preferredDeliveryHours: "08:00 - 16:00",
  },
  {
    id: "saban-40",
    name: "חולון תעשייה / המרכבה",
    comaxId: "51092",
    district: "מרכז",
    address: "המרכבה 26",
    city: "חולון",
    lat: 32.008,
    lng: 34.795,
    status: "standard",
    contactName: "יעקב גבאי",
    contactPhone: "054-9988117",
    craneBarcode: "18310",
    flatbedBarcode: "818310",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 24.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "אזור תעשייה ראשי, גישה נוחה לכל סוגי המשאיות, שטח תפעולי רחב.",
    preferredDeliveryHours: "כל שעות הפעילות",
  },
  {
    id: "saban-41",
    name: "ראשון מערב / משה דיין",
    comaxId: "51103",
    district: "מרכז",
    address: "שדרות משה דיין 33",
    city: "ראשון לציון",
    lat: 31.988,
    lng: 34.771,
    status: "standard",
    contactName: "שלומי אזולאי",
    contactPhone: "050-6655449",
    craneBarcode: "18311",
    flatbedBarcode: "818311",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 27.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "סמוך למתחם הסינמה סיטי, דרך גישה רחבה ללא מגבלת משקל או גובה.",
    preferredDeliveryHours: "07:30 - 15:30",
  },
  {
    id: "saban-42",
    name: "ראשון מרכז / הרצל",
    comaxId: "51214",
    district: "מרכז",
    address: "הרצל 65",
    city: "ראשון לציון",
    lat: 31.965,
    lng: 34.801,
    status: "problematic",
    contactName: "בני אלבז",
    contactPhone: "052-3322118",
    craneBarcode: "18312",
    flatbedBarcode: "818312",
    craneUnloadMinutes: 40,
    flatbedUnloadMinutes: 25,
    distanceKm: 28.1,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 620,
    observations: "ציר מרכזי צפוף, עבודות תשתית ברחוב, תנועת הולכי רגל כבדה.",
    riskDetails: "חסימת מעבר מחייבת אישור עירייה מראש. מומלץ לתאם הגעה מוקדמת.",
    preferredDeliveryHours: "06:00 - 07:30 בבוקר",
  },
  {
    id: "saban-43",
    name: "ראש העין פסגות / נחל רבה",
    comaxId: "51325",
    district: "מרכז",
    address: "נחל רבה 18",
    city: "ראש העין",
    lat: 32.087,
    lng: 34.965,
    status: "standard",
    contactName: "יוסי דהאן",
    contactPhone: "054-7766559",
    craneBarcode: "18313",
    flatbedBarcode: "818313",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 11.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "שכונת פסגות אפק החדשה, אתר בנייה פעיל, גישה נוחה למשאית מנוף.",
    preferredDeliveryHours: "07:00 - 16:00",
  },
  {
    id: "saban-44",
    name: "פארק סיבל / עמל",
    comaxId: "51436",
    district: "מרכז",
    address: "עמל 12",
    city: "ראש העין",
    lat: 32.102,
    lng: 34.945,
    status: "standard",
    contactName: "משה שמש",
    contactPhone: "050-1122998",
    craneBarcode: "18314",
    flatbedBarcode: "818314",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 9.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "פארק הייטק ותעשייה, כבישים רחבים מאוד, חניות פריקה מסומנות.",
    preferredDeliveryHours: "כל שעות הפעילות",
  },
  {
    id: "saban-45",
    name: "יהוד בינוי / מוהליבר",
    comaxId: "51547",
    district: "מרכז",
    address: "מוהליבר 30",
    city: "יהוד-מונוסון",
    lat: 32.031,
    lng: 34.889,
    status: "standard",
    contactName: "דוד רובין",
    contactPhone: "052-8899114",
    craneBarcode: "18315",
    flatbedBarcode: "818315",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 16.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 620,
    observations: "מתחם פינוי בינוי גדול, רחבת התארגנות מרוצפת בטון למשאיות חומרי בניין.",
    preferredDeliveryHours: "08:00 - 16:00",
  },

  // --- 46 to 55: שפלה ומודיעין (מודיעין-מכבים-רעות, שהם, רמלה, לוד, רחובות, נס ציונה) ---
  {
    id: "saban-46",
    name: "מודיעין כרמים / עמק האלה",
    comaxId: "60101",
    district: "שפלה / מודיעין",
    address: "עמק האלה 44",
    city: "מודיעין-מכבים-רעות",
    lat: 31.895,
    lng: 35.008,
    status: "standard",
    contactName: "אביעד קופר",
    contactPhone: "054-4455889",
    craneBarcode: "18401",
    flatbedBarcode: "818401",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 38.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "כבישי עמק רחבים, פריקה מעל חומת אבן מדורגת לגינה פנימית.",
    preferredDeliveryHours: "08:00 - 15:00",
  },
  {
    id: "saban-47",
    name: "מודיעין מוריה / שרה אמנו",
    comaxId: "60212",
    district: "שפלה / מודיעין",
    address: "שרה אמנו 19",
    city: "מודיעין-מכבים-רעות",
    lat: 31.884,
    lng: 35.019,
    status: "problematic",
    contactName: "יורם חכים",
    contactPhone: "050-9988223",
    craneBarcode: "18402",
    flatbedBarcode: "818402",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 25,
    distanceKm: 40.2,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 780,
    observations: "רחוב גבעי עם שיפוע קיצוני, חניות רכבים תלולות. חובה רגלי מנוף מחוזקות בבלוקי עץ.",
    riskDetails: "שיפוע כביש 14%, חובה בלוקי עץ תחת רגלי מנוף וסדי בלימה.",
    preferredDeliveryHours: "10:00 - 13:00 בלבד",
  },
  {
    id: "saban-48",
    name: "שהם כרמים / תמר",
    comaxId: "60323",
    district: "שפלה / מודיעין",
    address: "התמר 14",
    city: "שהם",
    lat: 31.998,
    lng: 34.945,
    status: "standard",
    contactName: "גלעד נווה",
    contactPhone: "052-6655112",
    craneBarcode: "18403",
    flatbedBarcode: "818403",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 21.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "ישוב קהילתי שקט ומסודר, גישה ישירה ללא פקקים מכביש 444.",
    preferredDeliveryHours: "08:00 - 15:30",
  },
  {
    id: "saban-49",
    name: "לוד מתחדשת / החשמונאים",
    comaxId: "60434",
    district: "שפלה / מודיעין",
    address: "החשמונאים 32",
    city: "לוד",
    lat: 31.952,
    lng: 34.891,
    status: "standard",
    contactName: "עאדל שוואקי",
    contactPhone: "054-2211448",
    craneBarcode: "18404",
    flatbedBarcode: "818404",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 26.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "פרויקט מגורים חדש במרכז לוד, משטח פריקה סלול ומגודר.",
    preferredDeliveryHours: "07:30 - 15:30",
  },
  {
    id: "saban-50",
    name: "רמלה מערב / הרצל",
    comaxId: "60545",
    district: "שפלה / מודיעין",
    address: "הרצל 80",
    city: "רמלה",
    lat: 31.927,
    lng: 34.869,
    status: "problematic",
    contactName: "אבי פרץ",
    contactPhone: "050-8877113",
    craneBarcode: "18405",
    flatbedBarcode: "818405",
    craneUnloadMinutes: 40,
    flatbedUnloadMinutes: 25,
    distanceKm: 29.5,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 780,
    observations: "ציר ראשי עמוס מסחר, קווי מתח עיליים קרובים מאוד לחזית המבנה.",
    riskDetails: "קרבת כבלי מתח עליון (פחות מ-3 מטר) – אסור להניף מנוף ללא ניתוק זמני.",
    preferredDeliveryHours: "06:00 - 07:30 בבוקר בלבד",
  },
  {
    id: "saban-51",
    name: "רחובות מדע / דרך יבנה",
    comaxId: "60656",
    district: "שפלה / מודיעין",
    address: "דרך יבנה 22",
    city: "רחובות",
    lat: 31.895,
    lng: 34.799,
    status: "standard",
    contactName: "מתן שטיין",
    contactPhone: "052-4433119",
    craneBarcode: "18406",
    flatbedBarcode: "818406",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 34.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "סמוך למכון ויצמן, כביש רחב ונוח, פריקה ישירה לתוך שטח המגרש.",
    preferredDeliveryHours: "08:30 - 15:30",
  },
  {
    id: "saban-52",
    name: "נס ציונה לב / ויצמן",
    comaxId: "60767",
    district: "שפלה / מודיעין",
    address: "ויצמן 45",
    city: "נס ציונה",
    lat: 31.931,
    lng: 34.798,
    status: "standard",
    contactName: "ליאור זמיר",
    contactPhone: "054-9977665",
    craneBarcode: "18407",
    flatbedBarcode: "818407",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 30.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "ציר ראשי, מפרץ פריקה פתוח, פריקת משטחי בלוקים ודבקים.",
    preferredDeliveryHours: "09:00 - 14:30",
  },
  {
    id: "saban-53",
    name: "באר יעקב / שדרות האלונים",
    comaxId: "60878",
    district: "שפלה / מודיעין",
    address: "שדרות האלונים 11",
    city: "באר יעקב",
    lat: 31.942,
    lng: 34.832,
    status: "standard",
    contactName: "שמעון גולן",
    contactPhone: "050-7766114",
    craneBarcode: "18408",
    flatbedBarcode: "818408",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 28.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "שכונה צומחת, גישה מהירה מכביש 4313, משטח פריקה יצוק.",
    preferredDeliveryHours: "07:30 - 16:00",
  },
  {
    id: "saban-54",
    name: "מבוא מודיעים / הלוחמים",
    comaxId: "60989",
    district: "שפלה / מודיעין",
    address: "הלוחמים 5",
    city: "מבוא מודיעים",
    lat: 31.935,
    lng: 34.982,
    status: "standard",
    contactName: "חיים בלום",
    contactPhone: "052-1188334",
    craneBarcode: "18409",
    flatbedBarcode: "818409",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 31.0,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "מושב כפרי שקט, אין עומסי תנועה, שטח פתוח לפריקה ללא מגבלה.",
    preferredDeliveryHours: "08:00 - 16:00",
  },
  {
    id: "saban-55",
    name: "כפר חב\"ד / בית הר\"מ",
    comaxId: "61090",
    district: "שפלה / מודיעין",
    address: "בית הר\"מ 12",
    city: "כפר חב\"ד",
    lat: 31.989,
    lng: 34.855,
    status: "standard",
    contactName: "מנחם מענדל",
    contactPhone: "054-3322990",
    craneBarcode: "18410",
    flatbedBarcode: "818410",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 22.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "גישה נוחה מכביש 44, חצר ישיבה גדולה, פריקת משטחי גבס ומלט.",
    preferredDeliveryHours: "08:00 - 17:00",
  },

  // --- 56 to 63: יהודה ושומרון ואזורי תעשייה מזרחיים (אריאל, עלי זהב, ברקן, אלפי מנשה, קרני שומרון, אורנית) ---
  {
    id: "saban-56",
    name: "אריאל אקדמיה / רמת הגולן",
    comaxId: "70101",
    district: "יהודה ושומרון",
    address: "רמת הגולן 33",
    city: "אריאל",
    lat: 32.106,
    lng: 35.185,
    status: "standard",
    contactName: "אלכסנדר ברודסקי",
    contactPhone: "050-8822331",
    craneBarcode: "18501",
    flatbedBarcode: "818501",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 36.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "נסיעה דרך כביש 5 (חוצה שומרון), מעבר מחסום שער שומרון. גישה פתוחה לאתר.",
    preferredDeliveryHours: "08:00 - 15:30",
  },
  {
    id: "saban-57",
    name: "אריאל מרכז / מוריה",
    comaxId: "70212",
    district: "יהודה ושומרון",
    address: "מוריה 14",
    city: "אריאל",
    lat: 32.102,
    lng: 35.172,
    status: "standard",
    contactName: "ולרי מלמוד",
    contactPhone: "052-7766119",
    craneBarcode: "18502",
    flatbedBarcode: "818502",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 35.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "בניין משותף, חניה רחבה, פריקה מעל מעקה אבן למחסן קבלן.",
    preferredDeliveryHours: "08:30 - 15:00",
  },
  {
    id: "saban-58",
    name: "ברקן אזור תעשייה / הגפן",
    comaxId: "70323",
    district: "יהודה ושומרון",
    address: "רחוב הגפן 20",
    city: "אזור תעשייה ברקן",
    lat: 32.115,
    lng: 35.112,
    status: "standard",
    contactName: "יוסי פנחס",
    contactPhone: "054-6644228",
    craneBarcode: "18503",
    flatbedBarcode: "818503",
    craneUnloadMinutes: 20,
    flatbedUnloadMinutes: 15,
    distanceKm: 28.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "אזור תעשייה מרכזי ומסודר, משטחי פריקה גדולים, פריקה נוחה עם מלגזה.",
    preferredDeliveryHours: "כל שעות הפעילות",
  },
  {
    id: "saban-59",
    name: "עלי זהב הרחבה / הדגן",
    comaxId: "70434",
    district: "יהודה ושומרון",
    address: "הדגן 8",
    city: "עלי זהב",
    lat: 32.078,
    lng: 35.088,
    status: "problematic",
    contactName: "נתנאל קראוס",
    contactPhone: "050-4411993",
    craneBarcode: "18504",
    flatbedBarcode: "818504",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 25,
    distanceKm: 26.2,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 780,
    observations: "כביש גישה צר ומפותל עם עליות חדות. יש לבדוק בלמים ומשקל מטען טרם יציאה.",
    riskDetails: "שיפועי כביש חדים ודרכי עפר לא סלולות בהרחבה. סכנת החלקה בחורף.",
    preferredDeliveryHours: "08:30 - 14:00 בלבד",
  },
  {
    id: "saban-60",
    name: "אורנית נוף / השיטה",
    comaxId: "70545",
    district: "יהודה ושומרון",
    address: "השיטה 22",
    city: "אורנית",
    lat: 32.131,
    lng: 34.995,
    status: "standard",
    contactName: "עופר לב",
    contactPhone: "052-3344110",
    craneBarcode: "18505",
    flatbedBarcode: "818505",
    craneUnloadMinutes: 25,
    flatbedUnloadMinutes: 18,
    distanceKm: 13.5,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "צמוד לכפר קאסם וכביש 5, ישוב קהילתי שקט, רחוב רחב ללא הפרעה.",
    preferredDeliveryHours: "07:30 - 15:30",
  },
  {
    id: "saban-61",
    name: "אלפי מנשה / גלבוע",
    comaxId: "70656",
    district: "יהודה ושומרון",
    address: "הגלבוע 18",
    city: "אלפי מנשה",
    lat: 32.171,
    lng: 35.018,
    status: "standard",
    contactName: "צחי ינאי",
    contactPhone: "054-8899221",
    craneBarcode: "18506",
    flatbedBarcode: "818506",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 16.2,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "עליה מפותלת דרך כביש 55, ישוב מסודר, פריקה מעל גדר לגינה פרטית.",
    preferredDeliveryHours: "08:00 - 15:00",
  },
  {
    id: "saban-62",
    name: "קרני שומרון / שד׳ מנשה",
    comaxId: "70767",
    district: "יהודה ושומרון",
    address: "שדרות מנשה 30",
    city: "קרני שומרון",
    lat: 32.164,
    lng: 35.099,
    status: "standard",
    contactName: "מאיר גלבוע",
    contactPhone: "050-5544118",
    craneBarcode: "18507",
    flatbedBarcode: "818507",
    craneUnloadMinutes: 30,
    flatbedUnloadMinutes: 20,
    distanceKm: 25.8,
    paymentTerms: "שוטף + 30",
    surchargePercent: 0,
    basePriceNis: 780,
    observations: "נסיעה דרך מעבר אליהו, כביש 55. מתחם מסחרי שכונתי, גישה חופשית לפריקה.",
    preferredDeliveryHours: "08:30 - 15:00",
  },
  {
    id: "saban-63",
    name: "פדואל מצפה / כנרת",
    comaxId: "70878",
    district: "יהודה ושומרון",
    address: "כנרת 15",
    city: "פדואל",
    lat: 32.062,
    lng: 35.068,
    status: "problematic",
    contactName: "חנן רוזן",
    contactPhone: "052-9911442",
    craneBarcode: "18508",
    flatbedBarcode: "818508",
    craneUnloadMinutes: 45,
    flatbedUnloadMinutes: 25,
    distanceKm: 27.5,
    paymentTerms: "מזומן / אשראי מראש",
    surchargePercent: 10,
    basePriceNis: 780,
    observations: "מרפסת המדינה, גובה טופוגרפי ניכר, רוחות עזות בשעות אחר הצהריים.",
    riskDetails: "רוחות חזקות עלולות לסכן עבודת מנוף עם משטחים קלים (לוחות קלקר, בידוד).",
    preferredDeliveryHours: "בוקר מוקדם (07:30-10:30) בלבד",
  },
]

export const HISTORICAL_63_CLIENTS: ClientSite[] = RAW_HISTORICAL_63_CLIENTS.map((c) => {
  const craneMinutes = c.craneUnloadMinutes || 25
  const flatbedMinutes = c.flatbedUnloadMinutes || 15
  const gps = `${c.lat.toFixed(6)}, ${c.lng.toFixed(6)}`

  return {
    ...c,
    hasExactGps: true,
    gpsCoordinates: gps,
    gpsSource: "sheet_col_p" as const,
    craneUnloadMinutes: craneMinutes,
    ituranCraneAvgMinutes: craneMinutes,
    flatbedUnloadMinutes: flatbedMinutes,
    ituranFlatbedAvgMinutes: flatbedMinutes,
    verificationStamp: "אימות רב-חודשי (אוג׳-ספט׳): הצלבת איתוראן עלי (איסוזו FSR90) + חכמת (מרצדס 2543) • שטח מאומת 100%",
    crossValidationNote: `הצלבת שטח רב-חודשית אוגוסט-ספטמבר: מנוף PTO ${craneMinutes} דק׳ (חכמת - מרצדס Actros 2543), פריקה ידנית/משטח ${flatbedMinutes} דק׳ (עלי - איסוזו FSR90). קואורדינטות שער כניסה שטח (${gps}) אומתו ב-100% מול יומן מסלולי איתוראן.`,
  }
})

/**
 * Searches the 63 clients by phone, name, contact, address, or comax ID
 */
export function searchClients(query: string): ClientSite[] {
  if (!query || !query.trim()) return []
  const clean = query.trim().toLowerCase().replace(/[-–—\s]/g, "")
  const rawWords = query.trim().toLowerCase().split(/\s+/).filter(Boolean)

  return HISTORICAL_63_CLIENTS.filter((client) => {
    // Phone match
    const cleanPhone = client.contactPhone.replace(/[-–—\s]/g, "")
    if (cleanPhone.includes(clean) || clean.includes(cleanPhone)) return true

    // Comax match
    if (client.comaxId === query.trim() || client.comaxId.includes(query.trim())) return true

    // Name / contact / address match
    const clientText = `${client.name} ${client.contactName} ${client.address} ${client.city} ${client.district}`.toLowerCase()
    return rawWords.every((word) => clientText.includes(word))
  })
}

/**
 * Normalizes input text and finds the single best matching client, or undefined
 */
export function findBestClientMatch(text: string): ClientSite | undefined {
  if (!text) return undefined

  // 1. Direct phone search
  for (const client of HISTORICAL_63_CLIENTS) {
    const rawPhoneDigits = client.contactPhone.replace(/\D/g, "")
    const textDigits = text.replace(/\D/g, "")
    if (rawPhoneDigits.length >= 7 && textDigits.includes(rawPhoneDigits)) {
      return client
    }
  }

  // 2. Comax ID search
  for (const client of HISTORICAL_63_CLIENTS) {
    if (text.includes(client.comaxId)) {
      return client
    }
  }

  // 3. Name or site search
  for (const client of HISTORICAL_63_CLIENTS) {
    if (text.includes(client.name)) return client
    if (client.contactName && text.includes(client.contactName)) return client
  }

  // 4. Address + city match
  for (const client of HISTORICAL_63_CLIENTS) {
    if (text.includes(client.address) || (text.includes(client.city) && text.includes(client.name.split("/")[0]?.trim()))) {
      return client
    }
  }

  return undefined
}
