import { GoogleGenAI } from "@google/genai"
import { NextRequest, NextResponse } from "next/server"

let aiClient: GoogleGenAI | null = null

function getGenAI(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY
    aiClient = new GoogleGenAI({ apiKey })
  }
  return aiClient
}

function pcmToWav(
  pcmBuffer: Buffer,
  sampleRate = 24000,
  numChannels = 1,
  bitsPerSample = 16,
): Buffer {
  const byteRate = sampleRate * numChannels * (bitsPerSample / 8)
  const blockAlign = numChannels * (bitsPerSample / 8)
  const wavHeader = Buffer.alloc(44)

  wavHeader.write("RIFF", 0)
  wavHeader.writeUInt32LE(36 + pcmBuffer.length, 4)
  wavHeader.write("WAVE", 8)
  wavHeader.write("fmt ", 12)
  wavHeader.writeUInt32LE(16, 16)
  wavHeader.writeUInt16LE(1, 20) // PCM
  wavHeader.writeUInt16LE(numChannels, 22)
  wavHeader.writeUInt32LE(sampleRate, 24)
  wavHeader.writeUInt32LE(byteRate, 28)
  wavHeader.writeUInt16LE(blockAlign, 32)
  wavHeader.writeUInt16LE(bitsPerSample, 34)
  wavHeader.write("data", 36)
  wavHeader.writeUInt32LE(pcmBuffer.length, 40)

  return Buffer.concat([wavHeader, pcmBuffer])
}

function cleanTextForSpeech(text: string): string {
  if (!text) return ""

  let clean = text
    // Remove Markdown buttons like 🔘 [ ... ]
    .replace(/🔘\s*`?\[\s*([^\]`]+?)\s*\]`?/gi, "")
    // Remove code blocks
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`([^`]+)`/g, "$1")
    // Remove links [title](url) -> title
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    // Remove Markdown headers (#, ##, ###)
    .replace(/^#+\s+/gm, "")
    // Remove bold/italics
    .replace(/(\*\*|__)(.*?)\1/g, "$2")
    .replace(/(\*|_)(.*?)\1/g, "$2")
    // Remove markdown list numbers and dashes
    .replace(/^\s*[-*+]\s+/gm, "")
    .replace(/^\s*\d+\.\s+/gm, "")
    // Remove horizontal rules
    .replace(/---+/g, "")
    // Remove table pipes
    .replace(/\|/g, " ")
    // Clean emojis that might confuse speech
    .replace(/[\u{1F300}-\u{1F9FF}]/gu, "")
    // Normalize spaces
    .replace(/\s+/g, " ")
    .trim()

  // Limit length to keep TTS responsive (~450 chars max for speech snippet)
  if (clean.length > 450) {
    const cut = clean.lastIndexOf(".", 420)
    if (cut > 200) {
      clean = clean.slice(0, cut + 1)
    } else {
      clean = clean.slice(0, 420) + "..."
    }
  }

  return clean
}

export async function POST(req: NextRequest) {
  try {
    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ error: "Missing GEMINI_API_KEY" }, { status: 500 })
    }

    const body = await req.json().catch(() => ({}))
    const rawText = body.text || ""

    const cleanedText = cleanTextForSpeech(rawText)
    if (!cleanedText) {
      return NextResponse.json({ error: "Text is empty or invalid" }, { status: 400 })
    }

    const ai = getGenAI()

    const promptText = `דברי בקול עברי נשי מלא, חם, טבעי ונעים: ${cleanedText}`

    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-tts-preview",
      contents: [{ parts: [{ text: promptText }] }],
      config: {
        responseModalities: ["AUDIO"],
        speechConfig: {
          voiceConfig: {
            // 'Kore' is a warm, natural female voice
            prebuiltVoiceConfig: { voiceName: "Kore" },
          },
        },
      },
    })

    const candidate = response.candidates?.[0]?.content?.parts?.[0]
    const base64Audio = candidate?.inlineData?.data

    if (!base64Audio) {
      return NextResponse.json(
        { error: "No audio data generated by TTS model" },
        { status: 502 },
      )
    }

    const pcmBuffer = Buffer.from(base64Audio, "base64")
    const wavBuffer = pcmToWav(pcmBuffer, 24000, 1, 16)
    const uint8Array = new Uint8Array(wavBuffer)

    return new NextResponse(uint8Array, {
      status: 200,
      headers: {
        "Content-Type": "audio/wav",
        "Content-Length": wavBuffer.length.toString(),
        "Cache-Control": "public, max-age=86400",
      },
    })
  } catch (error: any) {
    console.error("TTS API error:", error)
    return NextResponse.json(
      { error: error?.message || "Internal server error in TTS" },
      { status: 500 },
    )
  }
}
